### ISSUE TITLE
StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above

### ISSUE THREAD

**Issue by Clemente420** [YunYang1994/TensorFlow2.0-Examples#99]
Traceback (most recent call last):
  File "video_demo.py", line 59, in <module>
    pred_bbox = model.predict_on_batch(image_data)
  File "/home/qw/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1157, in predict_on_batch
    outputs = self.predict_function(inputs)
  File "/home/qw/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3740, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/home/qw/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/home/qw/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/qw/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/qw/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/qw/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv2d/Conv2D (defined at /home/qw/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_keras_scratch_graph_13297]

Function call stack:
keras_scratch_graph

**Comment by Clemente420** [comment]
for tensorflow 2.xx

add these to your code can fix

`import tensorflow as tf 
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.compat.v1.InteractiveSession(config=config)`

**Comment by Clemente420** [comment]
import tensorflow as tf 
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.compat.v1.InteractiveSession(config=config)

**Comment by shaoxiang777** [comment]
> import tensorflow as tf
> config = tf.compat.v1.ConfigProto()
> config.gpu_options.allow_growth = True
> session = tf.compat.v1.InteractiveSession(config=config)

Thanks! It works for me. tf 2.3
